### ISSUE TITLE
`update` operation fails when no fields needs to be changed

### ISSUE THREAD

**Issue by rwillians** [TurtleAI/derive#16]
```txt
20:20:54.630 [error] ** (Ecto.QueryError) `update_all` requires at least one field to be updated in query:

from t0 in Hatch.TimeTracker.Models.TimeEntry,
  where: t0.id == ^"30806491569410975171616041336832",
  update: [set: []]

    (ecto 3.8.3) lib/ecto/repo/queryable.ex:205: Ecto.Repo.Queryable.execute/4
    (ecto 3.8.3) lib/ecto/multi.ex:742: Ecto.Multi.apply_operation/4
    (ecto 3.8.3) lib/ecto/multi.ex:723: Ecto.Multi.apply_operation/5
    (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.8.3) lib/ecto/multi.ex:697: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto_sql 3.8.1) lib/ecto/adapters/sql.ex:1221: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.4.2) lib/db_connection.ex:865: DBConnection.transaction/3
    (ecto 3.8.3) lib/ecto/repo/transaction.ex:18: Ecto.Repo.Transaction.transaction/4
    (derive 0.1.0) lib/derive/ecto/operation/update.ex:16: anonymous fn/6 in Derive.Ecto.DbOp.Derive.Ecto.Operation.Update.to_multi/2
    (ecto 3.8.3) lib/ecto/multi.ex:723: Ecto.Multi.apply_operation/5
    (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.8.3) lib/ecto/multi.ex:697: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto_sql 3.8.1) lib/ecto/adapters/sql.ex:1221: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.4.2) lib/db_connection.ex:1562: DBConnection.run_transaction/4
```

The problem is on https://github.com/TurtleAI/derive/blob/master/lib/derive/ecto/operation/update.ex#L21-L25

We need another pattern match where, If the map of fields is empty (`map_size(fields) == 0`), then we perform a no-op -- just skip and do nothing.

**Comment by rwillians** [comment]
@venkatd I notice the code I linked (originally in an older issue in turtle-api) has changed. For the looks of it, the problem has been fixed.

Once you have a chance, can you confirm and close this issue?

**Comment by venkatd** [comment]
@rwillians it should be fixed and there's a test to cover it:
https://github.com/TurtleAI/derive/blob/master/test/ecto/operation_test.exs#L136-L140
